### ISSUE TITLE
grid的merge可能在aoi_update后没有设置为false,导致后续出问题

### ISSUE THREAD

**Issue by ssnobin** [lvzixun/aoi#1]
有grid_touch过才会清空merge，获得某个grid的ga_data就会生成merge，而获得某个grid的ga_data并不需要grid_touch该grid，只需有观察者出现在该grid旁边。

**Comment by ssnobin** [comment]
`local function test3()
    local b = os.clock()
    local n = 10000
    local aoi_obj = aoi.aoi_new(9, 9, 1, 1)
    for i=1,n do
        aoi_obj:aoi_add(i, MAKER_MARK|WATCHER_MARK, 0, 0)
    end
    local e1 = os.clock()
    print("test after_add:", e1 - b)
    local ret = aoi_obj:aoi_update()
    --{watcherid:[{makerid:xx}]} 其中{makerid:xx}只有一份，都是引用
    --PrintTable(ret)
    local e2 = os.clock()
    print("test cost:", e2 - b)
    for times =1,10 do
        for i = 1,10000 do
            local x = math.random(0,8)
            local y = math.random(0,8)
            aoi_obj:aoi_set(i,x,y)
            if i%100 == 0 then
                aoi_obj:aoi_update()
            end
        end
    end
    local e3 = os.clock()
    print("test total_cost:", e3 - b)
end`

**Comment by lvzixun** [comment]
看下这个提交： https://github.com/lvzixun/aoi/commit/cca56bbb06990294a3571f37650847717c2eb4e2  生成merge的时候有问题，对于没有修改的grid应该不设置merge。
